# register
POST http://localhost:8081/api/users
content-type: application/json

{
  "user":{
    "username": "Jacob4",
    "email": "jake2@jake.com.vn",
    "password": "jakejake"
  }
}

# login
POST http://localhost:8081/api/users/login
content-type: application/json

{
  "user":{
    "email": "jake2@jake.com.vn",
    "password": "jakejake"
  }
}

# get current
GET http://localhost:8081/api/user
content-type: application/json
authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWtlQGpha2UuY29tLnZuIiwidXNlcl9pZCI6ODU4MzI4Njk1NjcwNDA3MTY5LCJleHAiOjE2ODIwMTYwNjN9.lQTSIG0VkPRuJdOe2FpeWlfVjsDXuXmWC7OoeJ0SitE

# update user
PUT http://localhost:8081/api/user
content-type: application/json
authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWtlQGpha2UuY29tLnZuIiwidXNlcl9pZCI6ODU4MzI4Njk1NjcwNDA3MTY5LCJleHAiOjE2ODIwMTYwNjN9.lQTSIG0VkPRuJdOe2FpeWlfVjsDXuXmWC7OoeJ0SitE

{
  "user": {
    "email": "nsdaaaaaaew@gmail.com"
  }
}
