# register
POST http://localhost:8081/api/users
content-type: application/json

{
  "user":{
    "username": "Jacob2",
    "email": "jake@jake.com",
    "password": "jakejake"
  }
}

# login
POST http://localhost:8081/api/users/login
content-type: application/json

{
  "user":{
    "email": "jake@jake.com",
    "password": "jakejake"
  }
}

# get current
GET http://localhost:8081/api/user
content-type: application/json
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWtlQGpha2UuY29tIiwidXNlcl9pZCI6ODU1NTg0MjAxNzM5ODI5MjQ5LCJleHAiOjE2ODExNzgxMDd9.qDCOkUL0kLrSC_xiFVS_zWJhe5LR2rgjglWv1S0qFjM
